# Generated by Django 4.2.6 on 2023-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='title')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='anons')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
